### PR TITLE
Download pre-built Ranger

### PR DESCRIPTION
**Pull request by pan3793**
I have uploaded the pre-built Apache Ranger v2.4.0 at https://github.com/pan3793/ranger/releases/tag/release-ranger-2.4.0

To simplify the process, prefer to download in default, users could also build by themselves and copy the outputs to `$PWD/download/` manually

### CODE REVIEW

**Comment by pan3793** [comment]
Also, cc @yanghua @SteNicholas

**Comment by Yikf** [comment]
Should we also remove the [build directory](https://github.com/awesome-kyuubi/hadoop-testing/tree/master/build/ranger)?

**Comment by pan3793** [comment]
> Should we also remove the [build directory](https://github.com/awesome-kyuubi/hadoop-testing/tree/master/build/ranger)?

yea, removed

**Review by Yikf — APPROVED** [review]

**Comment by pan3793** [comment]
@Yikf thanks for review, merged

**Comment by yanghua** [comment]
> Also, cc @yanghua @SteNicholas

thanks, @pan3793 nice feature!

**Pull request merged**
