### PR TITLE
#21 Export HADOOP_CLASSPATH for hadoop-master1

### LINKED ISSUE #21: Export HADOOP_CLASSPATH for hadoop-master1

### PR DESCRIPTION
**Pull request by yanghua**
Fix #21

### CODE REVIEW

**Comment by pan3793** [comment]
does HMS and HS2 works as expected?

**Comment by yanghua** [comment]
> does HMS and HS2 work as expected?



> does HMS and HS2 work as expected?

hold on, will check it.

**Comment by yanghua** [comment]
> does HMS and HS2 work as expected?

I did some simple test cases via kyuubi beeline, it seems everything is OK.

**Review by pan3793 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
